spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cus_spring?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: tse@9527
    driver-class-name: com.mysql.jdbc.Driver
  #\u5173\u95ED\u9ED8\u8BA4\u6A21\u677F\u5F15\u64CE
  thymeleaf:
    cache: false
    enabled: false
  http:
    encoding:
      force-response: true
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  redis:
    database: 0
    host: localhost
    port: 6379